### ISSUE TITLE
Wrong truth table for kleene_implication

### ISSUE THREAD

**Issue by powlpy** [novacrazy/rust-tribool#1]
According to the [wikipedia page](https://en.wikipedia.org/wiki/Three-valued_logic#Kleene_and_Priest_logics), the kleene_implication function is not equivalent to `a OR b` but  `NOT(a) OR b`.

**Comment by novacrazy** [comment]
Ah, I apologize for that. It's fixed now.

**Comment by novacrazy** [comment]
I'm curious, what kind of application are you using tribool in? I've never had a use for it myself.

**Comment by powlpy** [comment]
In fact, I had made my own version of tribool then by researching I came across yours. In comparing with mine, I noticed the error. But I confess that neither have I ever used it.

**Comment by novacrazy** [comment]
Yeah, I just liked how easy Rust makes expressing actual truth tables as `match` expressions. Since you went through the effort of making your own, is there anything I can add to mine since I already kind of took the crate name?

**Comment by powlpy** [comment]
My version did not have many functions, you already implemented everything I had put.
